// npm i @react-native-community/masked-view
// npm i @react-native-firebase/app
// npm i @react-native-firebase/database
// npm i @react-navigation/bottom-tabs
// npm i @react-navigation/native
// npm i @react-navigation/stack
// npm i react
// npm i react-icons
// npm i react-native
// npm i react-native-date-picker
// npm i react-native-fbsdk
// npm i react-native-gesture-handler
// npm i react-native-paper
// npm i react-native-reanimated
// npm i react-native-safe-area-context
// npm i react-native-screens
// npm i react-native-vector-icons
// npm i react-navigation
// npm i react-redux
// npm i redux
// npm i redux-thunk